import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// app/layout.tsx
export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}


